### ISSUE TITLE
problem loading mathjax on osx 10.10

### ISSUE THREAD

**Issue by kindlychung** [mathjax/MathJax#1135]
Here is the error msg from console:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full

The website concerned is math.stackexchange.com.

I have tried on firefox 36, chrome 41, and opera 28 with the same result.
This problem does not seem to exist for Linux systems.

**Comment by pkra** [comment]
I suspect this is a duplicate of the CDN issues described at https://github.com/mathjax/MathJax/issues/1133

**Comment by kindlychung** [comment]
Why does this have anything to do with DNS servers? My Linux machine should be using the very same DNS servers, but it doesn't have problems loading mathjax.

**Comment by pkra** [comment]
> Why does this have anything to do with DNS servers?

It's just a guess since our provider is being attacked. If you have more data on why the loading fails, please let us know.

> My Linux machine should be using the very same DNS servers, but it doesn't have problems loading mathjax.

Again, just a guess. In any case, it's been erratic for most people, failing for a few minutes, hours or days.

**Comment by pkra** [comment]
The CDN issue was resolved according to our CDN hoster. We hope this problem has disappeared.

**Comment by kindlychung** [comment]
Still the same. From math.stackexchange:

 Prove that $\mathrm{Ind}_{\mathbb{I}}^G \cong \mathbb{C}[G]$

**Comment by pkra** [comment]
Thanks for the follow up. Are you able to ping cdn.mathjax.org (or at least www.mathjax.org)?

**Comment by kindlychung** [comment]
Yes, I can ping the site:

    ping cdn.mathjax.org
    PING cdn.mathjax.org (127.0.0.1): 56 data bytes
    64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.057 ms
    64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.120 ms
    64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.126 ms
    64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.110 ms
    64 bytes from 127.0.0.1: icmp_seq=4 ttl=64 time=0.116 ms

**Comment by pkra** [comment]
Thanks. Can you access http://cdn.mathjax.org/mathjax/latest/MathJax.js on its own?

**Comment by kindlychung** [comment]
I got 404:

    Not Found

    The requested URL /mathjax/latest/MathJax.js was not found on this server.

**Comment by pkra** [comment]
Sorry for not having ready your previous comment carefully (I was travelling). The ping suggests that cdn.mathjax.org resolves to localhost -- have you re-routed the cdn via a local hosts file?

**Comment by kindlychung** [comment]
Oh, my goodness, how careless of me! I had a line in my /etc/hosts:

    127.0.0.1 cdn.mathjax.org

Thanks for the help!

**Comment by pkra** [comment]
Thanks for confirming -- glad that's all it took after all.
